class AdviceService {
  AdviceService._();

  static const _conseys = {
    'Sante': [
      'Pran 8 vè dlo chak jou pou yon bon idratasyon.',
      'Dòmi 7-8 èdtan chak nwit pou repoze kò w.',
      'Fè egzèsis 30 minit chak jou pou kenbe fòm.',
      'Manyen tèt ou regilyèman pou detekte boul nan sen.',
      'Vizite jinekolog ou chak 6 mwa.',
      'Lave men w avan ak apre w fin ale nan twalèt.',
      'Siveye sik règ ou pou konnen kò w pi byen.',
      'Pran vitamin fanm chak jou pou sante w.',
      'Pa janm sote manje, manje balanse.',
      'Tcheke tansyon w regilyèman.',
      'Evite fimen ak bwè alkòl anpil.',
      'Fè tès VIH chak 3 mwa si w aktif seksyèlman.',
      'Pran swen dan ou — brese 2 fwa pa jou.',
      'Fè egzamen tete chak mwa apre règ ou.',
      'Konsilte doktè si w santi doulè ekstròdinè.',
      'Pratike yoga pou soulaje tansyon ak estrès.',
      'Evite twòp sik nan manje pou anpeche dyabèt.',
      'Manje fwi ak legim chak jou.',
      'Fè tès pap chak 3 ane apre 21 an.',
      'Pran solèy 15 minit chak maten pou vitamin D.',
    ],
    'Relasyon': [
      'Kominike klè ak patnè w sou santiman w yo.',
      'Pa janm aksepte vyolans nan relasyon ou.',
      'Ou merite respè ak lanmou tout bon.',
      'Pa pè di NON lè w pa santi w alèz.',
      'Konfyans se baz tout relasyon ki an sante.',
      'Pase tan ak moun ki fè w santi w byen.',
      'Relasyon pozitif ede w grandi.',
      'Si yon moun pa respekte w, kite l ale.',
      'Pratike padon pou geri kè w.',
      'Chache konsey si relasyon w gen pwoblèm.',
      'Relasyon sana mande ekilib ak konpwomi.',
      'Pa konpare relasyon w ak sa lòt moun genyen.',
      'Rezève tan pou tèt ou nan relasyon w.',
      'Eksprime rekonesans pou patnè w chak jou.',
      'Aprann di tcheke m pa okipe.',
      'Yon relasyon pa dwe fè w pèdi idantite w.',
      'Fè aktivite ansanm pou ranfòse lyen.',
      'Koute plis pale nan relasyon w.',
      'Pa janm fòse yon relasyon ki pa mache.',
      'Sèks dwe konsanty, san presyon ak san danje.',
    ],
    'Sikolojik': [
      'Pratike meditasyon 10 minit chak maten.',
      'Ekri santiman w nan jounal pèsonèl.',
      'Pa janm ezite mande èd si w santi w deprime.',
      'Pale ak yon sikològ si w santi w bezwen.',
      'Fè respirasyon gwo pou kalme tèt ou.',
      'Sèvi afimasyon pozitif chak jou.',
      'Kris la se yon faz, li pap dire tout tan.',
      'Pratike gratitid — ekri 3 bagay ou rekonesan.',
      'Yon ti mizik kalme ka chanje atitid ou.',
      'Anviwònman w afekte sante mantal ou — netwaye l.',
      'Pran yon ti poz nan travay la pou detann tèt ou.',
      'Pale ak fanm ou fè konfyans.',
      'Egzèsis fizik melanje ak sante mantal.',
      'Pa rete nan izolasyon — rete konekte.',
      'Sispann konpare tèt ou ak lòt moun.',
      'Fè yon bagay ou renmen chak jou.',
      'Dòmi se medikaman pou sèvo a.',
      'Anbrase enpèfeksyon ou — yo fè w moun.',
      'Sèvi aplikasyon relaksasyon pou jere estrès.',
      'Chak jou se yon nouvo kòmansman.',
    ],
    'Edikasyon': [
      'Li yon paj chak jou pou ogmante konesans ou.',
      'Aprann yon nouvo mo chak jou nan yon lòt lang.',
      'Enskri nan yon fòmasyon gratis sou entènèt.',
      'Li sou dwa fanm pou konnen pwoteksyon ou.',
      'Edikasyon se zam ki pi pwisan nan mond lan.',
      'Patisipe nan seminè sou sante seksyèl.',
      'Anseye lòt fanm sa w aprann.',
      'Fè rechèch sou kontrasepsyon chwazi bon metòd.',
      'Koute podcast edikatif pandan w ap travay.',
      'Yon fanm edike se yon fanm lib.',
      'Aprann jere lajan ou pou endepandans finansye.',
      'Konsilte bibliyotèk gratis sou entènèt.',
      'Swiv kou sou sante mantal ak byennèt.',
      'Edikasyon seksyèl pwoteje w kont maladi.',
      'Patisipe nan gwoup diskisyon fanm.',
      'Aprann teknik deba pou defann dwa w.',
      'Li sou istwa fanm kap batay.',
      'Konesans sou sik règ ou ede w planifye.',
      'Enfòme w sou maladi kwonik ak prevansyon.',
      'Televizyon pa ka ranplase yon bon liv.',
    ],
    'Dwa Fanm': [
      'Ou gen dwa viv san vyolans.',
      'Ou gen dwa di non nan tout sikonstans.',
      'Ou gen dwa chwazi moun w vle marye.',
      'Ou gen dwa al lekòl ak etidye.',
      'Ou gen dwa travay ak gen pwòp lajan ou.',
      'Ou gen dwa chwazi kantite pitit ou vle.',
      'Ou gen dwa aksè swen sante.',
      'Lwa pwoteje w kont agresyon seksyèl.',
      'Si w santi w an danje, rele 133 oswa 116.',
      'An Ayiti, lwa kondane vyolans domestik.',
      'Ou gen dwa possession tè ak pwopriyete.',
      'Pa kite pèsonn fè w santi w enferyè.',
      'Dwa fanm se dwa moun.',
      'An Ayiti, Lwa sou Vyolans Famasyal egziste.',
      'Si yon moun fè w mal, pote plent nan tribinal.',
      'Kontrasepsyon se yon dwa ou genyen.',
      'Ou gen dwa patisipe nan politik.',
      'Nou tout gen dwa viv ak diyite.',
      'Edikasyon se dwa ou, pa yon privilèj.',
      'Egalite fanm ak gason se lalwa.',
    ],
    'Byennèt': [
      'Pratike swen pèsonèl chak jou.',
      'Ba tèt ou yon jou konje san telefòn.',
      'Fè yon mask figi natirèl ak zaboka.',
      'Pran yon beny cho ak sèl Epsom pou detann.',
      'Fè yon masaj tèt pou soulaje tansyon.',
      'Achte yon bon krèm pou po w.',
      'Pran swen cheve w ak yon mask natirèl.',
      'Fè yon ti pwomnad nan lanati.',
      'Jwenn yon amoni ant travay ak lavi prive.',
      'Jete sa w pa bezwen pou anviwònman an.',
      'Fè yon lis objektif pou semèn nan.',
      'Ofri tèt ou yon ti kado chak semèn.',
      'Sèvi zak an lwil esansyèl pou kalme.',
      'Fè etid trankilite chak maten.',
      'Sèvi krèm solèy chak jou pou pwoteje po w.',
      'Chita trankil 5 minit san fè anyen.',
      'Mete abiye ou fè w santi w bèl.',
      'Fè yon règ san tele en nan wikenn nan.',
      'Chante yon chante ou renmen.',
      'Danse nan chanm ou san pèsonn pa wè.',
    ],
  };

  static Map<String, List<String>> get conseys => Map.unmodifiable(_conseys);
  static List<String> get categories => _conseys.keys.toList();

  static List<String> conseysByCategory(String cat) => _conseys[cat] ?? [];

  static String randomConsey() {
    final cat = _conseys.keys.elementAt(DateTime.now().microsecondsSinceEpoch % _conseys.length);
    final conseys = _conseys[cat]!;
    return conseys[DateTime.now().millisecondsSinceEpoch % conseys.length];
  }

  static String randomConseyByCategory(String cat) {
    final conseys = _conseys[cat];
    if (conseys == null || conseys.isEmpty) return '';
    return conseys[DateTime.now().microsecondsSinceEpoch % conseys.length];
  }
}
