import 'dart:math';

class SpiritualService {
  SpiritualService._();
  static final _rand = Random();

  static final _verses = [
    {'text': 'Fanm ki gen krentif pou Senyè a, se li ki merite fè lwanj.', 'ref': 'Pwovèb 31:30'},
    {'text': 'Ou gen anpil valè nan je Bondye.', 'ref': 'Lik 12:7'},
    {'text': 'Pa janm pè, paske mwen avèk ou.', 'ref': 'Ezayi 43:2'},
    {'text': 'Bondye fè ou fò epi vanyan.', 'ref': 'Jozwe 1:9'},
    {'text': 'Ou se limyè nan mond lan.', 'ref': 'Matye 5:14'},
    {'text': 'Mwen kapab tout bagay ak Kris la k ap ban mwen fòs.', 'ref': 'Filipyen 4:13'},
    {'text': 'Pale byen sou tèt ou.', 'ref': 'Pwovèb 31:25'},
    {'text': 'Bondye renmen ou ak yon renmen etènel.', 'ref': 'Jeremi 31:3'},
    {'text': 'Chak jou se yon nouvo kòmansman.', 'ref': 'Plent 3:23'},
    {'text': 'Pa dekouraje, Bondye pap janm kite ou.', 'ref': 'Detewonomi 31:6'},
    {'text': 'Ou te fèt pou yon rezon.', 'ref': 'Jeremi 29:11'},
    {'text': 'Bondye wè tout batay ou.', 'ref': 'Sam 56:8'},
    {'text': 'Fès ou soti nan Bondye.', 'ref': 'Ezayi 40:29'},
    {'text': 'Pa pè pou w mande èd.', 'ref': 'Matye 7:7'},
    {'text': 'Lapè avèk ou.', 'ref': 'Jan 14:27'},
    {'text': 'Se pou Bondye ba w fòs ak ankourajman.', 'ref': 'Ezayi 41:10'},
    {'text': 'Ou se yon manman vanyan.', 'ref': 'Pwovèb 31:28'},
    {'text': 'Bondye konnen sa w bezwen.', 'ref': 'Matye 6:8'},
    {'text': 'Mache ak Bondye, w ap wè limyè.', 'ref': 'Jan 8:12'},
    {'text': 'Lavi a bèl ak Bondye.', 'ref': 'Sam 118:24'},
    {'text': 'Kontinye fè byen.', 'ref': 'Galat 6:9'},
    {'text': 'Bondye pap janm bliye ou.', 'ref': 'Ezayi 49:15'},
    {'text': 'Ou gen dwa viv ak kè poze.', 'ref': '2 Timote 1:7'},
    {'text': 'Bondye se refij ou.', 'ref': 'Sam 46:1'},
    {'text': 'Ou se pitit Bondye.', 'ref': 'Jan 1:12'},
    {'text': 'Senyè a ap gide w chak jou.', 'ref': 'Sam 23:1'},
    {'text': 'Bondye tande lapriyè w.', 'ref': 'Sam 66:19'},
    {'text': 'Yon fanm ki gen lafè, se yon forterès.', 'ref': 'Pwovèb 31:25'},
    {'text': 'Se pa laperèz ki soti nan Bondye.', 'ref': 'Romin 8:15'},
    {'text': 'Bondye ap prepare w pou bèl bagay.', 'ref': '1 Korintyen 2:9'},
    {'text': 'Ou gen yon pakèt fòs anndan w.', 'ref': 'Filipyen 4:6'},
    {'text': 'Pa janm pèdi espwa.', 'ref': 'Romin 15:13'},
    {'text': 'Bondye pap janm bay plis pase w kapab.', 'ref': '1 Korintyen 10:13'},
    {'text': 'Lapriyè se refij ou.', 'ref': 'Filipyen 4:6'},
    {'text': 'Ou se yon vanyan fanm.', 'ref': 'Pwovèb 31:10'},
    {'text': 'Bondye ap ba w sa w bezwen.', 'ref': 'Matye 6:31-32'},
    {'text': 'Kè w pa bezwen pè.', 'ref': 'Jan 14:27'},
    {'text': 'Travay w se yon benediksyon.', 'ref': 'Kolosyen 3:23'},
    {'text': 'Ou se yon mèvèy nan je Bondye.', 'ref': 'Sam 139:14'},
    {'text': 'Bondye pap janm abandonnen w.', 'ref': 'Ebre 13:5'},
    {'text': 'Chak maten se yon nouvo favè.', 'ref': 'Plent 3:22-23'},
    {'text': 'Ou gen fòs pou w chanje sa w vle.', 'ref': '2 Korintyen 12:9-10'},
    {'text': 'Se pa tout moun ki merite w.', 'ref': 'Pwovèb 13:20'},
    {'text': 'Vanyan fanm ki jwenn Bondye.', 'ref': 'Pwovèb 31:10'},
    {'text': 'Tout bagay ap mache byen pou ou.', 'ref': 'Romin 8:28'},
    {'text': 'Bondye ap ba w lajwa.', 'ref': 'Sam 30:5'},
    {'text': 'Ou pa bezwen pè lavni.', 'ref': 'Jeremi 29:11'},
    {'text': 'Senyè a ap bat pou ou.', 'ref': 'Egzòd 14:14'},
    {'text': 'Bondye wè tout sa w fè.', 'ref': 'Ebre 4:13'},
    {'text': 'Ou se yon kreyasyon bèl.', 'ref': 'Sam 139:14'},
  ];

  static final _prayers = [
    'Senyè, ban mwen fòs jodi a pou mwen fè fas ak tout defi. Gide m...',
    'Bondye, mwen remèt tout enkyetid mwen nan men ou. Ban mwen lapè...',
    'Papa, mwen mande w beni fanm kap li lapriyè sa a jodi a...',
    'Senyè, ouvri chemen pou mwen, ban m bon jan opòtinite...',
    'Bon Bondye, pwoteje mwen ak tout mwen renmen yo jodi a...',
    'Senyè, geri kè mwen, geri lespri mwen, geri kò mwen...',
    'Papa, ban mwen sajès pou mwen pran bon desizyon jodi a...',
    'Bondye, mwen di ou mèsi pou yon lòt jou. Mèsi pou lavi mwen...',
    'Senyè, mwen mande w pwoteje fanm kap sibi vyolans jodi a...',
    'Bon Bondye, ban mwen kouraj pou mwen pa janm bay vag...',
    'Papa, se pou volonte w fèt nan lavi mwen. Mwen fè konfyans...',
    'Senyè, mwen mande w padon pou tout peche mwen yo...',
    'Bondye, ouvri je mwen pou mwen wè sa w gen pou mwen...',
    'Papa, relege mwen lè mwen fatige. Ban mwen fòs...',
    'Senyè, beni travay men mwen, fè l grandi...',
    'Bon Bondye, mwen remèt fanmi mwen nan men ou...',
    'Papa, ban mwen yon kè rekonesan pou tout sa m genyen...',
    'Senyè, ede mwen jwenn lajan pou mwen soti nan pwoblèm...',
    'Bondye, ede mwen pran bon desizyon pou lavi mwen...',
    'Papa, mwen mande w pwoteje pitit mwen yo...',
    'Senyè, ban mwen lapè nan kè mwen...',
    'Bon Bondye, mwen di w mèsi paske w toujou la...',
    'Papa, ede mwen jwenn bon jan moun nan lavi mwen...',
    'Senyè, fè mwen wè limyè nan fen tinèl la...',
    'Bondye, mwen fè konfyans nan plan ou pou lavi mwen...',
    'Papa, ban mwen kouraj pou mwen padone moun ki fè m mal...',
    'Senyè, ede mwen grandi chak jou nan konesans ou...',
    'Bon Bondye, pwoteje mwen kont tout move lespri...',
    'Papa, ban mwen fòs pou mwen leve apre chak chit...',
    'Senyè, mwen mande w beni tout fanm k ap li sa...',
    'Bondye, ouvri pòt opòtinite pou mwen...',
    'Papa, ede mwen jere lajan mwen ak sajès...',
    'Senyè, ban mwen sante ak fòs...',
    'Bon Bondye, ede mwen rete fèm nan konfyans ou...',
    'Papa, mwen renmen w. Mwen di w mèsi pou tout bagay...',
  ];

  static Map<String, String> randomVerse() => _verses[_rand.nextInt(_verses.length)];
  static String randomPrayer() => _prayers[_rand.nextInt(_prayers.length)];
  static String randomVerseText() => _verses[_rand.nextInt(_verses.length)]['text'] ?? '';
  static String randomRef() => _verses[_rand.nextInt(_verses.length)]['ref'] ?? '';
}
